import './globals.css';
import React from 'react';
import type { Metadata } from 'next';

import StoreProvider from './StoreProvider';

export const metadata: Metadata = {
  title: 'Han Nom Recognition',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico?v=2" />
        <link rel="stylesheet" href="/stylesheets/global.css" />
      </head>
      <body suppressHydrationWarning={true}>
        <StoreProvider>
          <main className="font-poppins">{children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
