type RequestModel = {
  Model_id: string;
  Name: string;
  Description: string;
  Status: string;
  Content: string;
  Date: string;
};

export type RequestModelList = {
  Data: RequestModel[];
};

export const ListModel: RequestModelList = {
  Data: [
    {
      Model_id: '1',
      Name: 'Model 1',
      Description: 'Description 1',
      Status: 'Chờ xử lý',
      Content: 'Content 1',
      Date: '2025-02-10',
    },
    {
      Model_id: '2',
      Name: 'Model 2',
      Description: 'Description 2',
      Status: 'Chờ xử lý',
      Content: 'Content 2',
      Date: '2025-02-11',
    },
    {
      Model_id: '3',
      Name: 'Model 3',
      Description: 'Description 3',
      Status: 'Chờ xử lý',
      Content: 'Content 3',
      Date: '2025-02-12',
    },
    {
      Model_id: '4',
      Name: 'Model 4',
      Description: 'Description 4',
      Status: 'Chờ xử lý',
      Content: 'Content 4',
      Date: '2025-02-13',
    },
    {
      Model_id: '5',
      Name: 'Model 5',
      Description: 'Description 5',
      Status: 'Chờ xử lý',
      Content: 'Content 5',
      Date: '2025-02-14',
    },
    {
      Model_id: '6',
      Name: 'Model 6',
      Description: 'Description 6',
      Status: 'Chờ xử lý',
      Content: 'Content 6',
      Date: '2025-02-15',
    },
    {
      Model_id: '7',
      Name: 'Model 7',
      Description: 'Description 7',
      Status: 'Chờ xử lý',
      Content: 'Content 7',
      Date: '2025-02-16',
    },
    {
      Model_id: '8',
      Name: 'Model 8',
      Description: 'Description 8',
      Status: 'Chờ xử lý',
      Content: 'Content 8',
      Date: '2025-02-17',
    },
    {
      Model_id: '9',
      Name: 'Model 9',
      Description: 'Description 9',
      Status: 'Chờ xử lý',
      Content: 'Content 9',
      Date: '2025-02-18',
    },
    {
      Model_id: '10',
      Name: 'Model 10',
      Description: 'Description 10',
      Status: 'Chờ xử lý',
      Content: 'Content 10',
      Date: '2025-02-19',
    },
    {
      Model_id: '5',
      Name: 'Model 5',
      Description: 'Description 5',
      Status: 'Chờ xử lý',
      Content: 'Content 5',
      Date: '2025-02-14',
    },
    {
      Model_id: '6',
      Name: 'Model 6',
      Description: 'Description 6',
      Status: 'Chờ xử lý',
      Content: 'Content 6',
      Date: '2025-02-15',
    },
    {
      Model_id: '7',
      Name: 'Model 7',
      Description: 'Description 7',
      Status: 'Chờ xử lý',
      Content: 'Content 7',
      Date: '2025-02-16',
    },
    {
      Model_id: '8',
      Name: 'Model 8',
      Description: 'Description 8',
      Status: 'Chờ xử lý',
      Content: 'Content 8',
      Date: '2025-02-17',
    },
    {
      Model_id: '9',
      Name: 'Model 9',
      Description: 'Description 9',
      Status: 'Chờ xử lý',
      Content: 'Content 9',
      Date: '2025-02-18',
    },
    {
      Model_id: '10',
      Name: 'Model 10',
      Description: 'Description 10',
      Status: 'Chờ xử lý',
      Content: 'Content 10',
      Date: '2025-02-19',
    },
    {
      Model_id: '5',
      Name: 'Model 5',
      Description: 'Description 5',
      Status: 'Chờ xử lý',
      Content: 'Content 5',
      Date: '2025-02-14',
    },
    {
      Model_id: '6',
      Name: 'Model 6',
      Description: 'Description 6',
      Status: 'Chờ xử lý',
      Content: 'Content 6',
      Date: '2025-02-15',
    },
    {
      Model_id: '7',
      Name: 'Model 7',
      Description: 'Description 7',
      Status: 'Chờ xử lý',
      Content: 'Content 7',
      Date: '2025-02-16',
    },
    {
      Model_id: '8',
      Name: 'Model 8',
      Description: 'Description 8',
      Status: 'Chờ xử lý',
      Content: 'Content 8',
      Date: '2025-02-17',
    },
    {
      Model_id: '9',
      Name: 'Model 9',
      Description: 'Description 9',
      Status: 'Chờ xử lý',
      Content: 'Content 9',
      Date: '2025-02-18',
    },
    {
      Model_id: '10',
      Name: 'Model 10',
      Description: 'Description 10',
      Status: 'Chờ xử lý',
      Content: 'Content 10',
      Date: '2025-02-19',
    },
    {
      Model_id: '5',
      Name: 'Model 5',
      Description: 'Description 5',
      Status: 'Chờ xử lý',
      Content: 'Content 5',
      Date: '2025-02-14',
    },
    {
      Model_id: '6',
      Name: 'Model 6',
      Description: 'Description 6',
      Status: 'Chờ xử lý',
      Content: 'Content 6',
      Date: '2025-02-15',
    },
    {
      Model_id: '7',
      Name: 'Model 7',
      Description: 'Description 7',
      Status: 'Chờ xử lý',
      Content: 'Content 7',
      Date: '2025-02-16',
    },
    {
      Model_id: '8',
      Name: 'Model 8',
      Description: 'Description 8',
      Status: 'Chờ xử lý',
      Content: 'Content 8',
      Date: '2025-02-17',
    },
    {
      Model_id: '9',
      Name: 'Model 9',
      Description: 'Description 9',
      Status: 'Chờ xử lý',
      Content: 'Content 9',
      Date: '2025-02-18',
    },
    {
      Model_id: '10',
      Name: 'Model 10',
      Description: 'Description 10',
      Status: 'Chờ xử lý',
      Content: 'Content 10',
      Date: '2025-02-19',
    },
  ],
};
